included:
  - roomscan

excluded:
  - DerivedData
  - .build

disabled_rules:
  - todo
  - trailing_comma

opt_in_rules:
  - empty_count
  - first_where
  - redundant_nil_coalescing
  - sorted_imports

line_length:
  warning: 140
  error: 180

type_body_length:
  warning: 300
  error: 400

function_body_length:
  warning: 70
  error: 100

file_length:
  warning: 600
  error: 800

identifier_name:
  min_length: 2
  excluded:
    - id
    - x
    - y
    - z